"""Upload assembled part videos to YouTube, scheduled and paced.

Reuses the paste-ready descriptions in ``pipeline/descriptions/part_NN.md``
(generated by ``scripts/generate_descriptions.py``) — no metadata is
regenerated here. Videos are uploaded one at a time, each scheduled to go live
on a future date so the channel drip-feeds instead of dumping everything at
once. A ledger (``upload_state_file``) makes reruns safe: already-uploaded
parts are skipped.

Configure everything in the ``[youtube]`` section of ``configuration.cfg``.

Examples
--------
    # See exactly what would happen, in what order, with what publish dates:
    .venv/bin/python -m scripts.upload_to_youtube --dry-run

    # Upload everything pending, sequentially, with the configured pacing:
    .venv/bin/python -m scripts.upload_to_youtube

    # Upload just the next 3 pending parts:
    .venv/bin/python -m scripts.upload_to_youtube --limit 3

First-time setup
----------------
    uv add google-api-python-client google-auth-oauthlib google-auth-httplib2
    # then fill in youtube.client_secrets_file and youtube.publish_start_date
"""
from __future__ import annotations

import argparse

from src.publisher.youtube_uploader import (
    _build_service,
    channel_info,
    discover_parts,
    publish_at_for,
    publish_at_on,
    upload_parts,
)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Parse, schedule, and print the plan without uploading.",
    )
    ap.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Upload at most this many pending parts this run.",
    )
    ap.add_argument(
        "--delay",
        type=float,
        default=None,
        help="Override seconds to wait between uploads (default from config).",
    )
    ap.add_argument(
        "--list",
        action="store_true",
        help="List discovered parts + their scheduled publish dates and exit.",
    )
    ap.add_argument(
        "--whoami",
        action="store_true",
        help="Sign in and print which channel this token uploads to, then exit.",
    )
    ap.add_argument(
        "--part",
        type=str,
        default=None,
        help="Upload only these part number(s), comma-separated (e.g. 12 or 12,14). "
        "Each part keeps its own scheduled publishAt.",
    )
    ap.add_argument(
        "--publish-at",
        type=str,
        default=None,
        metavar="YYYY-MM-DD",
        help="Override the scheduled publish date for every part in this run "
        "(at the configured publish_time/timezone). e.g. --publish-at 2026-07-04",
    )
    args = ap.parse_args()

    if args.whoami:
        ch = channel_info(_build_service())
        if ch:
            handle = f" ({ch['customUrl']})" if ch.get("customUrl") else ""
            print(f"Channel: {ch['title']}{handle}\nID: {ch['id']}")
        else:
            print("Could not resolve a channel for this token.")
        return

    if args.list:
        parts = discover_parts()
        print(f"{len(parts)} uploadable parts:\n")
        for p in parts:
            try:
                when = publish_at_for(p.part_num - 1)
            except ValueError as exc:
                when = f"<{exc}>"
            print(f"  {p.key}: {p.title}")
            print(f"      file: {p.video_path.name}")
            print(f"      publishAt: {when}\n")
        return

    parts = None
    if args.part:
        wanted = {int(x) for x in args.part.replace(" ", "").split(",") if x}
        parts = [p for p in discover_parts() if p.part_num in wanted]
        found = {p.part_num for p in parts}
        missing = wanted - found
        if missing:
            print(f"No description/part found for: {sorted(missing)}")
        if not parts:
            return

    override = publish_at_on(args.publish_at) if args.publish_at else None
    upload_parts(
        parts=parts,
        dry_run=args.dry_run,
        limit=args.limit,
        delay_seconds=args.delay,
        publish_at_override=override,
    )


if __name__ == "__main__":
    main()
